#!/bin/csh
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7 and revised by Yunsen Zhang at 06/05/2022

# This folder contains GROMACS formatted CHARMM36 force fields, a pre-optimized PDB structure, and GROMACS inputs.
# All input files were optimized for GROMACS 2019.2 or above, so lower version of GROMACS can cause some errors.
# We adopted the Verlet cut-off scheme for all minimization, equilibration, and production steps because it is 
# faster and more accurate than the group scheme. If you have a trouble with a performance of Verlet scheme while 
# running parallelized simulation, you should check if you are using appropriate command line.
# For MPI parallelizing, we recommand following command:
# mpirun -np $NUM_CPU gmx21  mdrun -ntomp 1

init=step5_ready
rest_prefix=step5_ready
mini_prefix=step6.0_minimization
equi_prefix=step6.%d_equilibration
prod_prefix=step7_production
prod_step=step7

# Minimization
# In the case that there is a problem during minimization using a single precision of GROMACS, please try to use 
# a double precision of GROMACS only for the minimization step.
gmx  grompp -f mdp/${mini_prefix}.mdp -o ${mini_prefix}.tpr -c ${init}.gro -r ${rest_prefix}.gro -p topol.top -n index.ndx -maxwarn 99
gmx  mdrun -v -deffnm ${mini_prefix} -ntmpi 1 -ntomp 8



# Equilibration
cnt=1
cntmax=6

while [ $cnt -le $cntmax ]
do
    pcnt=`expr $cnt - 1`
    istep=`printf ${equi_prefix} ${cnt}`
    pstep=`printf ${equi_prefix} ${pcnt}`
    if [ ${cnt} == 1 ]; then pstep=${mini_prefix};fi

    gmx  grompp -f mdp/${istep}.mdp -o ${istep}.tpr -c ${pstep}.gro -r ${rest_prefix}.gro -p topol.top -n index.ndx -maxwarn 99
    gmx  mdrun -v -deffnm ${istep} -ntmpi 1 -ntomp 12 -gpu_id 0 
    let cnt++
done

# Production
cnt=1
cntmax=1

while [ $cnt -le $cntmax ]
do
    pcnt=`expr ${cnt} - 1`
    istep=${prod_step}_${cnt}
    pstep=${prod_step}_${pcnt}

	if [ ${cnt} == 1 ] 
	then
        pstep=`printf ${equi_prefix} 6`
        gmx  grompp -f mdp/${prod_prefix}.mdp -o ${istep}.tpr -c ${pstep}.gro -p topol.top -n index.ndx -maxwarn 99 -r ${pstep}.gro
	else
        gmx  grompp -f ${prod_prefix}.mdp -o ${istep}.tpr -c ${pstep}.gro -t ${pstep}.cpt -p topol.top -n index.ndx -maxwarn 99 -r ${pstep}.gro
	fi
        gmx  mdrun -v -deffnm ${istep} -ntmpi 1 -ntomp 8 -gpu_id 0 
    
    let cnt++

done

mv step7_1.gro step7_production.gro 

gmx grompp -f mdp/pull.mdp -c step7_production.gro -r step7_production.gro -p topol.top -maxwarn -1 -o pull.tpr -n index.ndx

gmx mdrun -deffnm pull -ntmpi 1 -ntomp 24 -pin on -v 

gmx sasa -f pull.trr -s pull.tpr -n index.ndx -surface 'pep'  -output '"Hydrophobic" group "pep" and charge {-0.2 to 0.2}; "Hydrophilic" group "pep" and not charge {-0.2 to 0.2}'

# python area.py area.xvg

gmx rms -s pull.tpr -f pull.trr -o rmsd.xvg <<EOF
3
3
EOF

gmx gyrate -s pull.tpr -f pull.trr -o gyrate.xvg <<EOF
3
EOF

python rmsd_gyrate.py rmsd.xvg gyrate.xvg

python merge.py rmsd.xvg gyrate.xvg merge.xvg

gmx sham -tsham 315 -nlevels 100 -f merge.xvg -ls gibbs.xpm -g gibbs.log -lsh enthalpy.xpm -lss entropy.xpm

python xpm2png.py -ip yes -f gibbs.xpm
# python xpm2png.py -ip yes -f entropy.xpm
# python xpm2png.py -ip yes -f enthalpy.xpm
# python xpm2png.py -ip yes -f prob.xpm

dit xpm2csv -f gibbs.xpm -o gibbs.csv

python gibbs_utils.py gibbs.csv merge.xvg area.xvg

rm bindex.ndx ener.xvg gibbs.log enthalpy.xpm entropy.xpm gibbs.xpm prob.xpm

gmx covar -s pull.tpr -f pull.trr -o eigenvalues.xvg -v eigenvectors.trr -xpma covapic.xpm <<EOF
3
3
EOF

python xpm2png.py -ip yes -f covapic.xpm

gmx anaeig -s pull.tpr -f pull.trr -v eigenvectors.trr -first 1 -last 1 -proj pc1.xvg <<EOF
3
3
EOF


gmx anaeig -s pull.tpr -f pull.trr -v eigenvectors.trr -first 2 -last 2 -proj pc2.xvg <<EOF
3
3
EOF

python merge.py pc1.xvg pc2.xvg merge_pc.xvg

gmx sham -tsham 315 -nlevels 100 -f merge_pc.xvg -ls gibbs_pc.xpm -g gibbs_pc.log -lsh enthalpy_pc.xpm -lss entropy_pc.xpm


python xpm2png.py -ip yes -f gibbs_pc.xpm

dit xpm2csv -f gibbs_pc.xpm -o gibbs_pc.csv

python pca_util.py gibbs_pc.csv merge_pc.xvg 

rm average.pdb covar.log covapic.xpm eigenvalues.xvg eigenvectors.trr bindex.ndx ener.xvg enthalpy_pc.xpm entropy_pc.xpm gibbs_pc.log gibbs_pc.xpm prob.xpm